apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: springboot-app-deploy
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.global.registry }}/{{ .Values.image }}:latest
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.port }}
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery:8761/eureka/
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://configserver:8888
