apiVersion: v2
name: spring-cloud-microservices
description: Spring Cloud Movie Recommendation Microservices
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: discovery
    version: 0.1.0
    repository: "file://charts/discovery"
  - name: configserver
    version: 0.1.0
    repository: "file://charts/configserver"
  - name: user
    version: 0.1.0
    repository: "file://charts/user"
  - name: movie
    version: 0.1.0
    repository: "file://charts/movie"
  - name: recommendation
    version: 0.1.0
    repository: "file://charts/recommendation"
  - name: gateway
    version: 0.1.0
    repository: "file://charts/gateway"
  - name: moviesui
    version: 0.1.0
    repository: "file://charts/moviesui"
  - name: hystrix
    version: 0.1.0
    repository: "file://charts/hystrix"
