version: '2'
services:
  discovery:
    image: kbastani/discovery-microservice
    ports:
      - "8761:8761"

  configserver:
    image: kbastani/config-microservice
    ports:
      - "8888:8888"
    depends_on:
      - discovery

  user:
    image: kbastani/users-microservice
    depends_on:
      - discovery
      - configserver

  movie:
    image: kbastani/movie-microservice
    depends_on:
      - discovery
      - configserver

  recommendation:
    image: kbastani/recommendation-microservice
    depends_on:
      - discovery
      - configserver

  gateway:
    image: kbastani/api-gateway-microservice
    ports:
      - "10000:10000"
    depends_on:
      - discovery
      - configserver
      - user
      - movie
      - recommendation

  moviesui:
    image: kbastani/movies-ui
    ports:
      - "9006:9006"
    depends_on:
      - discovery
      - configserver

  hystrix:
    image: kbastani/hystrix-dashboard
    ports:
      - "7979:7979"
    depends_on:
      - gateway
      - discovery